Repository C4-Smoketrees/blog, pull requests merged in 2020-05, with the labels that each got.

#4 blog-preview: Multiple improvements
  package-lock.json
  package.json
  src/components/blog/blog.jsx
  src/components/pages/blog-edit/blog-edit.jsx
  src/components/preview/preview.js
  src/routes/blog-id.js
  src/static/public/styles/global.css
Labels: enhancement, vulnerability

#5 routes: Add a 404 page
  src/components/entrypoints/not-found.jsx
  src/components/pages/not-found/not-found.jsx
  src/routes/not-found.js
  src/server.js
  src/views/pages/not-found.ejs
  webpack.config.js
Labels: enhancement

#6 blog: Add profile pic support
  package-lock.json
  package.json
  src/components/blog/blog.jsx
  src/components/pages/blog-id/blog-id.jsx
  src/components/preview/preview.js
  src/routes/blog-id.js
  src/routes/login.js
  src/static/public/styles/global.css
Labels: enhancement

#7 treewide: Add save snackbars
  package-lock.json
  package.json
  src/components/navbar/navbar.js
  src/components/pages/create-blog/create-blog.jsx
  src/components/preview/preview.js
  src/logging/logger.js
  src/middleware/jwt-decrypt.js
  src/routes/sign-up.js
  src/server.js
  src/static/public/styles/global.css
Labels: enhancement

#8 Fix logout and markdown
  package-lock.json
  package.json
  src/components/blog/blog.jsx
  src/components/navbar/navbar.js
  src/components/pages/blog-edit/blog-edit.jsx
  src/components/pages/create-blog/create-blog.jsx
  src/components/preview/preview.js
  src/routes/logout.js
  src/server.js
  src/static/public/styles/global.css
Labels: bug, enhancement

#9 Fix markdown
  src/static/public/styles/global.css
  src/static/public/styles/prism.css
Labels: bug, enhancement
